Desktop version
fmshot2/My-Portfolio pull request #4
Opened 2022-09-30 16:53 UTC by fmshot2

2022-09-30 18:32 UTC, Kamba56 requested changes
Hi @fmshot2, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] All linters passed 👏👏👏
- [x] Great use of Github flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [Optional] Please make sure that each of your commit messages should be written in the imperative tense and capitalized. This will make your work look more professional. A good example of a professional commit message is *Add markup to index.html* and a bad example is *added HTML*. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8).


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 18:32 UTC, Kamba56 commented on index.html
> +                            <li>
- [ ] Please use an indentation of two spaces in all your documents for readability. This is [best practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) and a convention.

2022-09-30 18:32 UTC, Kamba56 commented on index.html
> +                </svg>
- [ ] Please note that all images that are only for decoration purposes should be added as background image in your CSS file. Kindly move these SVG images to your CSS file. This is best practice. You can use [multiple background images](https://www.w3schools.com/css/css3_backgrounds.asp) to do this.

2022-09-30 18:32 UTC, Kamba56 commented on index.html
> +                </form>
- [ ] Kindly remove white spaces to the left and right of the form section and make the background image match the figma template.

- [ ] Kindly make the spacing between the form inputs equal to match the figma template.
### Your design
![2](https://user-images.githubusercontent.com/94551484/193333390-6fde3ed2-54de-41d3-8d81-de217856d946.png)![3](https://user-images.githubusercontent.com/94551484/193333435-fe6143dc-dc04-430b-9c3d-34354965df87.png)
### Figma template

![f2](https://user-images.githubusercontent.com/94551484/193333577-fdd8ce0a-5f21-4904-b540-baa0d0dc808e.png)![f3](https://user-images.githubusercontent.com/94551484/193333620-b34c156b-1960-4835-a461-29bb12ab63e8.png)

2022-09-30 18:32 UTC, Kamba56 commented on index.html
> +                </ul>
- [ ] In the Figma template, this is a list of social icons, I noticed you have a list of technologies instead. Kindly fix this please as you are required to stick to design guidelines as much as possible.
- [ ] Kindly make the `Get resume` button a bit smaller to match the Figma template.
### Your design
![1](https://user-images.githubusercontent.com/94551484/193333883-8c92ffeb-712d-4f35-8342-6b0886ae57b4.png)

### Figma template
![f1](https://user-images.githubusercontent.com/94551484/193333930-d8436d1a-7e1a-44db-ba1d-cb12927028b7.png)

2022-10-01 12:11 UTC, emmiiorji approved these changes
Hi @fmshot2, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/193394444-b0f34938-8c62-449c-8950-4731348549e5.gif)


## Good Highlights✔

- Linter checks are passing
- Adherence to GitHub flow
- Good commit messages
- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 12:11 UTC, emmiiorji commented on style.css
> +}
[Optional] I recommend that you implement the curved left edge of the container of the contact form to follow the design. It would look great.

Your design:
![image](https://user-images.githubusercontent.com/20554583/193408965-ec81bc56-9438-4064-b423-f0b019c952a3.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/193408941-60eb63c7-c621-4007-aab5-d4a5df755127.png)

2022-10-12 12:23 UTC, merged